### PR TITLE
Social Proof Section

### LINKED ISSUE #59: Add social proof to website
- [x] Design & frontend work - @ghislaineguerin 
- [ ] Collect testimonials - @kgodey

### PR DESCRIPTION
**Pull request by ghislaineguerin**
Fixes #59

### CODE REVIEW

**Comment by kgodey** [comment]
Marking as draft because we don't want to merge this in until we have real testimonials.

**Comment by kgodey** [comment]
The design looks good! I'll leave this as a draft until I collect and update testimonials.

**Comment by ghislaineguerin** [comment]
@kgodey please take a look at the updated design. Once approved I will finalize the content and clean up / style.

**Review by kgodey — CHANGES_REQUESTED** [review]
Mathesar_Open_source_UI_for_Postgres_databases

@ghislaineguerin I annotated a screenshot with my feedback.

I assume you'll also update the other two landing pages once the main landing page design is finalized? We'll need to personalize which testimonials we show on which page (e.g. software engineer page should include all the newsletters, non-technical page should have different quotes)

**Pull request closed without merging**
