### PR TITLE
Feedback fixes

### LINKED ISSUE #44: Address website feedback
From Myra:

- [x] Capitalizing the 'W' in "How it Works" on the navigation bar
- [x] Adding a line "Please enter your email address" underneath the sign-up section heading to indicate what kind of information is needed
- [x] Adding bullet point icons next to the 3 questions on the non-technical page for easier scanning and information processing
- [x] Bolding certain words on the non-technical page for improved scanning and information processing
- [x] Emphasizing the line "But too many data tools limit you from managing your data your way" on the homepage to make it more prominent for skim readers
- [x] Reordering the use cases listed on the homepage to put the "prototype" use case first, since it may be more relevant for early adopters who are primarily developers
- [x] Making the 2nd call-to-action (CTA) on the homepage a different color to avoid confusion
- [x] Adding "(limited availability)" or making it more specific on the Request Installation page
- [x] Removing the comma after "But" on the About Us page
- [x] Correcting the misspelling of "embarrassing" on the non-technical page
- [x] Using the longer hyphen in the homepage headline for consistency
- [x] Adding a period after "wheel" on the homepage
- [x] Cutting out the last sentence "You can allow..." on the Dev How it Works page to avoid repetition
- [x] Modifying the highlighted sentence on the Non-Technical How it Works page for improved readability and emphasis on work productivity and efficiency.

From team:

- [x] Add GitHub logo with link to repo to header
- [x] Add Open Graph tags and preview the site after adding them
- [x] Add alt text to header logo image
- [ ] Improve a11y and mobile performance based on Chrome Lighthouse report (Won't fix as it requires the process to minify the css and js on the site)
- [x] Center "Stay updated on Mathesar's release" box when viewport is 1000px wide
- [x] Ensure proper heading structure with one h1 per page and proper heading nesting
- [x] Fix TOC overflow issue on FAQ page for small screens in landscape mode

### PR DESCRIPTION
**Pull request by ghislaineguerin**
Fixes #44

### CODE REVIEW

**Review by kgodey — CHANGES_REQUESTED** [review]
Thanks @ghislaineguerin, nice work overall!

### Changes requested
- [x] Myra's suggestion of "And bold the words: “without”, “faulty”, “quickly update”, “one view” on the non-technical user page is not implemented.
- [ ] "But too many data tools limit you from managing your data your way" emphasis on the homepage could be improved. Just the bold doesn't work - maybe consider using red for "limit" and green for "your way"? Or some other solution is fine too.
- [ ] "View on GitHub" link should include external link icon and open in new tab.
- [ ] Request installation page - "(limited slots available)" should be on a new line with some gap in between.
- [ ] Non-technical page - "Reshape your data structure" section: "**Ensure accurate data, without disruptions.**" should be on a separate paragraph and not bolded.
- [ ] I'm not sure if any of Brent's feedback from the email thread was fixed, I didn't see it on your list in #44
- [ ] I also didn't see Anish's dropdown issues in #44 – were they omitted intentionally? 

I didn't check the OpenGraph tags, I'll do that once this is merged and deployed.

**Comment by kgodey** [comment]
@ghislaineguerin For this point:

> Myra's suggestion of "And bold the words: “without”, “faulty”, “quickly update”, “one view” on the non-technical user page is not implemented.

I looked at the emphasized version you pushed in https://github.com/centerofci/mathesar-website/pull/46/commits/6c2effb4ad96a23386f05af4228acbfea85cef22 and it's not really visible as emphasis. Maybe we can use the same blue color you used on the homepage?

**Comment by ghislaineguerin** [comment]
@kgodey This is ready for review again. I needed to test out the new illustrations so I have included them here as well. We can merge if all other feedback is fine and then we can do additional updates if that's ok.

**Comment by kgodey** [comment]
We reviewed on a video call. Issues that need to be fixed:
- [ ] Remove text background color on homepage
- [ ] Make highlighted text on dark background sections blue
- [ ] Fix height difference in funder logos on small screens

**Review by kgodey — APPROVED** [review]

**Pull request merged**
