### PR TITLE
CTA and Mailing List Updates

### LINKED ISSUE #60: Update website CTAs to promote SaaS version and email list
Myra sent us several suggestions [here](https://docs.google.com/document/d/1tNFPelG8pMMN0zPH_XvbmE-e9o9v6qzxZkOXKibXxcI/edit). This issue will implement all the website related ones.

- [x] Homepage - 4 boxes changes 
- [x] Developer How it Works - 4 boxes changes
- [x] Mailing list CTA 
  - [x] add checkboxes to all pages
  - [x] update header and copy 
  - [x] Ensure checkboxes propagate to MailerLite - @kgodey 
- [x] Non-Technical How it Works
  - [x] update CTA buttons
  - [x] update mailing list CTA header
- [x] About Us page
  - [x] update sustainability copy - @kgodey 
- [x] FAQ page
  - [x] add new FAQ

### PR DESCRIPTION
**Pull request by ghislaineguerin**
Fixes #60

### CODE REVIEW

**Comment by ghislaineguerin** [comment]
@kgodey There are a couple of tasks left for you in #60.

**Review by kgodey — CHANGES_REQUESTED** [review]
@ghislaineguerin The center align makes this hard to read. We should left align form elements.
Screen Shot 2023-02-17 at 9 56 29 AM

I'm also wondering if we can save some space by putting the checkboxes next to each other for wider screens.

**Comment by kgodey** [comment]
@ghislaineguerin I made a few changes to the PR, all my assigned items are now resolved.

I think the mailing list CTA still looks a bit unbalanced, see screenshots at the end of this post. I think we should:
- Left align signup button
- Move checkboxes to different lines on small screens

Any other suggestions you have are appreciated.

Screen Shot 2023-02-17 at 14 52 47
Screen Shot 2023-02-17 at 2 54 50 PM

**Review by kgodey — CHANGES_REQUESTED** [review]
Please see comment in main thread.

**Review by kgodey — APPROVED** [review]

**Pull request merged**
